name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: windows-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Build
        run: dotnet publish

      - name: Zip
        run: zip DOOMLauncher-${{ github.ref }}.zip DOOMLauncher/bin/Release/net8.0-windows/win-x64/publish/DOOMLauncher.exe

      - name: Upload release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.SECRET_TOKEN }}
          file: ${{ github.workspace }}/DOOMLauncher-${{ github.ref }}.zip
          tag: ${{ github.ref }}
